services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: gojoye-backend
    env_file:
      - ./Backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: gojoye-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped
